modLoader="javafml" 

loaderVersion="[25,)" 

issueTrackerURL="http://my.issue.tracker/"

[[mods]] 

modId="randomarmormobs" 

version="1.0" 

displayName="RandomArmorMobs" 

updateJSONURL="http://myurl.me/" 

displayURL="https://www.curseforge.com/minecraft/mc-mods/randomarmormobs" 

logoFile="randomarmormobs.png" 

credits=""

authors="MORIMORI0317" 

description='''
Thank you for downloading!

'''
